Algoritmo "CALCULO MEDIA"

Var


   AP1, AP2, AS, MEDIA: real

Inicio

   escreva ("digite a nota AP1:")
   leia (AP1)
   escreva ("digite a nota AP2:")
   leia (AP2)
   escreva ("digite a nota AS:")
   leia (AS)
   
   MEDIA <- AP1 + AP2 + AS
   
   escreval ("Média:" ,MEDIA)
   
   se MEDIA >= 7 entao
   escreva ("Aprovado")
   senao
   escreva ("reprovado")
   
FIMSE

Fimalgoritmo